env:
    global:
        # travis encrypt GITHUB_USERNAME=$GITHUB_USERNAME
        - secure: "iwE1/wyEIrgli3AVccmtEkNyU4NVe6UThs0iL7YQ6vFwsMCJjrBzK0tCqccBx2Toz07JWa8CORL48BgHNfsZeDvKZvWW8JUjC6tmwJnAzzHY0s+2S3xEkaqWpuXrwjKTcZxzGuZ5IvXXXja1IpDSo+mMuU8ETp4V3aWp7alfpxjbi+shI7UYxz7nRmnCo0vWyrzTH5SeHm68EEjoXcD3QaF4DwTFBtmEZ3PtD88Gvt8HKF2VpuQoNruAzyLeinXX1Zprt2h67ee/uveAuRYMWLYQGWxynOowxFk46whLeL//QvGuR4FE3C3jXp4nbnoHjUoVOCeODHZ7HegqWE6mybCz5slE8ZlPaS8dKfRNHRWVnIqYWXpeRBV6FqaBGw7qp+iV3VfRb5rdnYRzoTEmguRI3TFb4RPkUhIW/cfco/zfoFXJDgpdwizUEv5I6TRqphGCvdJTnwMilYXK1PJg0yzw76tsRWPYqmF/i9CrbiHT5+Wgi0I2rGukmHMZhifFwy3jmreBXNBjG5/KZFbYpDG6+aHMDwyAheG4UYOzYUhLRU02U5TlAH67HHgf5y6GQh1RCROJOgIjBvOfPprL2FqWhG+9FJILBte3GH1czHXiGiAUltkC1V/5IZGxDKNhDsotBHltjs7DAvBF5yQ2T2lgw3IGhzNTvn0Z4cWaHDo="
        # travis encrypt TWINE_PASSWORD=$TWINE_PASSWORD
        - secure: "ieDarSvpKjIr9Ek3aVyMvVX/tIgAa/LiCtU5tRsLm+UnPqu9fwmFsl++oz0jP6IdJHK/cuX9pasA4Le8Ljk2E9+ywyD9ijUXKf2EpeLg4xAdKA/1MpbB+MyC3GBkUW+TV7y874gTtbg2acgi7klHyhYdF6zdbFnJtJcg8N8tOMUgFShwtMkvSvsilbspFAo+C+6TDQX8fiaECiyZ9MW+W0GSTgYX9Kc5YAi1TxCrfZc8QUivSZaMTxOlae7rJxXKoF6xZSyP1s3hY1n2tz+44bFnb5VP70W5025hSGMSSA1FuvIp3cV25HQekflKn2tICkLviUs7cMzZosbwQrBuneRYzKy1y9G5i4pheA2sTw/6ThQ1pGCK2yjdZy1fvyQ0acGn2hvKrWwIP2p5f0plFcGpnFqf5d+CNLHIQwabtmgJQA8u9o0Ac/m4gJutyTkpHTnZhuudUIBq70Nm82wZLSKQepUvurwWq+b6kdvhPY5F+Xa1EUWsq07Ap5FnVURAAoTNpU7P1BnTRjrVllAGeJvyB91SaODJG/xxfdh15YpvlfK0M/kjansMLXUQwpXRsBQwUqEI8X/lQIkxAFvnUcIgtXIX1CV4C0sEpjUc9ZmPdsWFBKgnjzr0urgV28/6o9uEQ/4qDKAbg/kM0djcVLyQ2h6jdLiNhUM3dMJDBlY="
        # travis encrypt GPG_OWNERTRUST=$GPG_OWNERTRUST
        - secure: "MmaYmMTtDtjE7v8b18BRoOKVBCuneLBeckcFV63L1TM3OvlMarOASdl1osDU00+4A9J4xInQax7B1C2PTpxCQGlGYMaA8iJAQBGSmjwfV4w+zDgW1J5cR/culERMtdm6Ba/BEPQ/47QX0oL2eLdTKOT5bZLyS8bJapc4pWFMTykm5s/vqbCQPIKfP6lGoRWMJ9o3ADLiFkxE01UbbP4oCgG2PR3imMXFNZNXdJYphKCRTGqw7SlSUfbKnEfgsfsBajEbApOHPwam8JaUB7cst1p1JfYePbJ8d8Ib8BMcWoRhNyLekuHjqIIr0/b10AvZ0ZQU9H75PLn5htS6leBsNRtyd0FLoLNRR02m6RFdQ9MnC90Kld8o+bv3+lvT87ErSM3SAUiIhbLaOFzdCS97jwPwaPWP06sMX3hEI8cJx//QvCcIA7By01XfLZXlmzxhEwNl4IpqOKQnPPEqptFFaMgjZ7TheCBo9lYyoVAuxOrlLK0/KgrcGAzo/p92V2nYGsEtyYJKgQFcJcSdm/CPRSpMERaR1b3bJqqeJdghvINBwBAkRm384MmijVkUlc3XnmHMLQeewdlaEE7ursiJfkXocbg65x8veNUIeZBB+IVLVu8acqmb9LFeE7J75aZ8XH46ooRxdziTWo0ZNeCd7+JsyumsD1SXUWADbs7uthk="

language: python
sudo: false

cache:
  apt: true
  directories:
  - $HOME/.cache/pip
  - $HOME/download
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
before_install:
  # Unpack encrypted GPG keys
  - openssl aes-256-cbc -K $encrypted_e3bb652dc81d_key -iv $encrypted_e3bb652dc81d_iv -in dev/travis_public_gpg_key.pgp.enc -out dev/travis_public_gpg_key.pgp -d
  - openssl aes-256-cbc -K $encrypted_e3bb652dc81d_key -iv $encrypted_e3bb652dc81d_iv -in dev/travis_secret_gpg_key.pgp.enc -out dev/travis_secret_gpg_key.pgp -d
  - pip install pip -U
  - pip install -r requirements.txt -U
install:
  - travis_retry pip install -e .
script: 
  #- travis_wait ./run_tests.py
  #- travis_wait python run_tests.py
  - travis_wait pytest --cov=xdoctest
after_success: 
    - codecov 
    - gpg --version
    - gpg2 --version
    - | 
        __heredoc__='''
        # HOW TO SETUP A GPG KEY
        #
        # References:
        # .. [1] https://github.com/travis-ci/travis.rb
        # .. [2] https://docs.travis-ci.com/user/encrypting-files/

        # After you have setup your GPG key (plenty of resources on google about how to do this)
        IDENTIFIER="travis-ci-Erotemic"
        KEYID=$(gpg --list-keys --keyid-format LONG "$IDENTIFIER" | head -n 2 | tail -n 1 | awk '{print $1}' | tail -c 9)
        echo "KEYID = $KEYID"

        cd $HOME/code/xdoctest
        gpg --armor --export-secret-keys $KEYID > dev/travis_secret_gpg_key.pgp
        gpg --armor --export $KEYID > dev/travis_public_gpg_key.pgp

        # Login to travis (requires authentication)
        source $(secret_loader.sh)
        travis login --github-token $GITHUB_TOKEN
        source $(secret_unloader.sh)
        
        # The following commands will output lines that will need to be
        # manually added to this file. You could run with --add, but it messes
        # up the formatting of this file. 
        travis encrypt-file dev/travis_secret_gpg_key.pgp dev/travis_secret_gpg_key.pgp.enc --force
        travis encrypt-file dev/travis_public_gpg_key.pgp dev/travis_public_gpg_key.pgp.enc --force

        # Export and encrpyt trust
        GPG_OWNERTRUST=$(gpg --export-ownertrust | base64)
        echo $GPG_OWNERTRUST
        echo "$GPG_OWNERTRUST" | base64 --decode
        travis encrypt GPG_OWNERTRUST="$GPG_OWNERTRUST"

        # Note: cant do this. travis gives a data too large error
        #GPG_SECRET_KEYS=$(gpg -a --export-secret-keys $IDENTIFIER | base64)
        #travis encrypt GPG_SECRET_KEYS="$GPG_SECRET_KEYS"

        '''  # <hack vim "regex" parser> '
    - cat dev/travis_public_gpg_key.pgp
    - | # Import GPG keys
        GPG_EXECUTABLE=gpg2
        $GPG_EXECUTABLE --import dev/travis_public_gpg_key.pgp
        $GPG_EXECUTABLE --import dev/travis_secret_gpg_key.pgp
        echo "$GPG_OWNERTRUST" | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
    - gpg --list-keys
    - |
        # Package and publish to pypi (if on release)
        echo "TRAVIS_BRANCH = $TRAVIS_BRANCH"
        if [ "$TRAVIS_BRANCH" == "release" ]; then
            # use set +x to log all intermediate commands 
            set +x
            pip install twine
            if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
              pip install six pyopenssl ndg-httpsclient pyasn1 -U --user
              pip install requests[security] twine --user
            elfi
            if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
              pip install six twine
              pip install --upgrade pyOpenSSL
            fi

            # TODO: reliable and secure gpg keys
            # Relies on a specific environmenmt being available 
            GPG_IDENTIFIER=travis-ci-Erotemic USE_GPG=True DEPLOY_BRANCH=release TAG_AND_UPLOAD=yes ./publish.sh
            set -x
        fi
